---
layout: default
title: 为啥你的None!=None
---

笔者最近在调试代码过程中，遇到一个比较有意思的问题，记录下来以积累经验。首先声明，笔者使用的语言是scala，版本是2.11。  

异常描述
----
代码在运行过程中偶现如下Error:
```
scala.MatchError: None (of class scala.None$)
        at com.xiaomi.common.thrift.SwiftProxyLike$class.call(ThriftFacade.scala:54)
        at com.xiaomi.common.thrift.ThriftProxy.call(ThriftFacade.scala:108)
        at com.xiaomi.common.thrift.ThriftProxy.apply(ThriftFacade.scala:146)
        at com.xiaomi.common.thrift.ThriftProxy.apply(ThriftFacade.scala:140)
```
抛出Error的代码如下，具体是在proxyConfig.endpoint match这一行抛出，如下所示：
```
protected def call[B](f: A => B, isAsync: Boolean)(implicit ctx: C): B = {
    proxyConfig.endpoint match {
        case None => contextCall(clientBuilder.build(), f)
        case Some(e) =>
            ... //此处代码省略
    }
}
```
其中proxyConfig实例类型是ThriftProxy，具体定义如下：
```
case class ThriftProxy[A](thriftClass: Class[A],
        endpoint: Option[Endpoint] = None
) extends SwiftProxyLike[A, Any] {}
```

问题追踪
----
首先通过Google，找到一条[线索](https://github.com/hierynomus/scalariform-gradle-plugin/issues/1), 其中解释如下：
```
debug the issue and looks like the problem is that Scalariform creates a new instance of None instead of using the singleton instance.I created 
a pull request to fix this. If you can merge it and release a new version with the fix I will really appreciate.
Regards,
Mariano A
```
简单翻译一下。在scala中，None是个单例对象，全局唯一。如果业务代码私自创建了一个None实例，进行匹配时会报这个Error。考虑到确定一个实例的唯一性，取决于实例所在地址和类加载器。于是在抛Error的地方加上日志，打印对象的地址和类加载器，确认endPoint和None是否是同一个实例，如下所示：
```
protected def call[B](f: A => B, isAsync: Boolean)(implicit ctx: C): B = {
    logger.info(s"trace endpoint, class: ${proxyConfig.thriftClass}, endPoint: ${proxyConfig.endpoint}, index: ${System.identityHashCode(proxyConfig.endpoint)}," + 
        "loader: ${proxyConfig.endpoint.getClass.getClassLoader}, none index: ${System.identityHashCode(None)}, loader: ${None.getClass.getClassLoader}")
    proxyConfig.endpoint match {
        case None => contextCall(clientBuilder.build(), f)
        case Some(e) =>
            ... //此处代码省略
    }
}
```

输入的日志如下：
```
[INFO  2022-03-17 16:28:09,692] - trace endpoint, class: interface com.xiaomi.ai.apicaps.thrift.AiApiCapsService$AsyncIface, endPoint: None, 
    index: 374126582, loader: AppClassloader@71a467, none index: 1231562525, loader: AppClassloader@71a467
```
从日志中可以发现，proxyConfig.endpoint 的确是None对象，并且和字面常量None不是同一个实例。手动写一个Demo来验证，可以确认如果实例不一样，的确会报scala.MatchError。具体代码如下所示：
```
//赋值为None
val none1 = None

//通过反射构造了一个None
val clas = this.getClass.getClassLoader.loadClass("scala.None$")
val constr = clas.getDeclaredConstructors()(0)
constr.setAccessible(true)
val none2 = constr.newInstance()

//再赋值一个None
val none3 = None

println(s"none1 == none2 is ${none1 == none2}")  //false
println(s"none1 == None3 is ${none1 == None}")   //false
println(s"none2 == None3 is ${none2 == None}")   //true

//抛出MatchError异常
none1 match {
    case None => println("test")
}
```
从这个Demo中可以发现，scala中的字面量None有些类似有java中的字符串常量，全局唯一。如果服务代码通过反射的方式创建一个私有的None，后续定义的常量None地址都会指向新创建的None, 这将导致创建前后定义的None，指向的不是同一个实例。  

至此，问题原因就比较清晰了。是由于服务代码私自创建了None，导致endPoint和None不是同一个实例，进而发生了MatchError。接下来需要找到代码中私自创建None的位置。在JVM中，创建一个对象，无论是何种方式都要调用对应的构造函数(克隆和ObjectStream例外)。笔者尝试通过对None的构造函数进行监听来确认。arthas是监听线上方法调用的利器，功能十分强大。笔者首先查看None有哪些方法，具体来说是具备多少个构造函数。如下所示：
```
[arthas@45564]$ sm scala.None$
scala.None$ <init>()V
scala.None$ canEqual(Ljava/lang/Object;)Z
scala.None$ productIterator()Lscala/collection/Iterator;
scala.None$ productPrefix()Ljava/lang/String;
scala.None$ productElement(I)Ljava/lang/Object;
scala.None$ productArity()I
scala.None$ get()Ljava/lang/Object;
scala.None$ get()Lscala/runtime/Nothing$;
scala.None$ toString()Ljava/lang/String;
scala.None$ hashCode()I
scala.None$ isEmpty()Z
scala.None$ readResolve()Ljava/lang/Object;
Affect(row-cnt:12) cost in 48 ms.
```

可以发现，只有一个构造函数，对这个构造函数进行监听，果然找到了调用链：
```
arthas@45564]$ stack scala.None$ <init>
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 189 ms, listenerId: 8
ts=2022-03-17 20:34:24;thread_name=default-dispatcher-8;id=272;is_daemon=false;priority=5;TCCL=jdk.internal.loader.ClassLoaders$AppClassLoader@7aec35a
    @scala.None$.<init>()
        at jdk.internal.reflect.GeneratedConstructorAccessor54.newInstance(null:-1)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at io.protostuff.runtime.RuntimeEnv$DefaultInstantiator.newInstance(RuntimeEnv.java:331)
        at io.protostuff.runtime.RuntimeSchema.newMessage(RuntimeSchema.java:487)
        at io.protostuff.runtime.RuntimeUnsafeFieldFactory$14$1.doMergeFrom(RuntimeUnsafeFieldFactory.java:1145)
        at io.protostuff.runtime.RuntimeDerivativeField$1.doMergeFrom(RuntimeDerivativeField.java:63)
        at io.protostuff.runtime.DerivativeSchema.mergeFrom(DerivativeSchema.java:99)
        at io.protostuff.GraphByteArrayInput.mergeFrom(GraphByteArrayInput.java:171)
        at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:503)
        at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:475)
        ...
```
从调用链明显可以发现，是在用protostuff进行序列化时，发生了None的创建。具体创建时机，笔者怀疑是当某个属性是None时，会触发创建。

结论
----
综合上述分析，是由于服务代码中使用protostuff进行序列化，在序列化过程中的某些特定时刻，创建None。导致字面量None的地址发生了变化，从而报MatchError。

解决办法
----
笔者看到网上有人遇到类似问题，并且也提供了一个解决办法，具体来说，就是修改一下match 匹配方式，如下所示：
```
protected def call[B](f: A => B, isAsync: Boolean)(implicit ctx: C): B = {
    proxyConfig.endpoint match {
        case x if(x.isInstanceOf[None$]) => contextCall(clientBuilder.build(), f)
        case Some(e) =>
```
针对这种解决办法，笔者想指出的是，出现这个问题本质上，是由于protostuff是为序列化java对象而提供的，虽然java和scala是共用同一套字节码的JVM语言，还是存在一定的不兼容。试想，如果在代码中已经存在了大量了 "case None" 就不好办了。因此在scala的项目开发中，我们尽量使用scala的特性，而不要因为"可以运行"，而不必要的引入一些java特性，出现类似问题排查起来有些麻烦。

关于None的一个有意思的现象
----
在调查问题的过程中，还发现None的一个有意思的现象, 也分享一下，代码如下所示：
```
val i = None
val a = Map("a" -> "b", "b" -> i)

// Prints X
a.get("b") match {
    case None => println("None")
    case Some(x) => println("X")
}
  
// Prints Non
a.get("c") match {
    case None => println("None")
    case Some(x) => println("X")
} 
```
实测发现，如果将scala中Map值设置为None，取出来的时候，实际值是Some(None)。可见在scala中，是不支持将Map的值设置为None。